#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd packages

# Azure
cd azure
pnpm lint-staged
cd ..

# Client
cd client
pnpm lint-staged
cd ..

# Terraform
cd terraform
terraform fmt
terraform validate
cd ..

cd ..